# 9)მომხმარებელს შემოატანინეთ ორი რიცხვი,თქვენი დავალებაა მოახდინოთ ყველა მათემატიკური ოპერაცია ამ რიცხვებზე, +,-./,//,*,==,%,ასევე კომენტარის სახით ახსენით რას აკეთებს % ნიშანი (ვინც აქამდე ჩამოხვედით და წინ რაც იყო ყველაფერი გააკეთეთ YOU ARE REAL CHADS!RESPECT❤️❤️❤️


ENTER_YOUR_FIRST_NUMBER = int(input("Enter your first number please, I'm begging you, ENTER IT RIGHT HERE: "))
ENTER_YOUR_SECOND_NUMBER = int(input("ENTER YOUR SECOND NUMBER OR I WILL FIND YOU AND DO A LOT OF ILLEGAL ACTIVITIES! YOU BETTER ENTER THAT NUMBER RIGHT HERE: "))

print(ENTER_YOUR_FIRST_NUMBER + ENTER_YOUR_SECOND_NUMBER)
print(ENTER_YOUR_FIRST_NUMBER - ENTER_YOUR_SECOND_NUMBER)
print(ENTER_YOUR_FIRST_NUMBER / ENTER_YOUR_SECOND_NUMBER)
print(ENTER_YOUR_FIRST_NUMBER // ENTER_YOUR_SECOND_NUMBER)
print(ENTER_YOUR_FIRST_NUMBER * ENTER_YOUR_SECOND_NUMBER)
print(ENTER_YOUR_FIRST_NUMBER == ENTER_YOUR_SECOND_NUMBER)
print(ENTER_YOUR_FIRST_NUMBER % ENTER_YOUR_SECOND_NUMBER)
print(ENTER_YOUR_SECOND_NUMBER - ENTER_YOUR_FIRST_NUMBER)
print(ENTER_YOUR_SECOND_NUMBER / ENTER_YOUR_FIRST_NUMBER)
print(ENTER_YOUR_SECOND_NUMBER // ENTER_YOUR_FIRST_NUMBER)
print(ENTER_YOUR_SECOND_NUMBER % ENTER_YOUR_FIRST_NUMBER)




