# 6) მომხმარებელს შემოატანინე ორი რიცხვი. ერთი float ტიპის, მეორე int ტიპის. და დაპრინტეთ ყველა შესაძლო მათემატიკური მოქმედება მათ შორის. (+, -, *, /, //, **, %)

x = float(input("Write a random float point number here: "))
y = int(input("Write a random intiger number here: "))
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x // y)
print(x ** y)
print(x % y)
print(y - x)
print(y / x)
print(y // x)
print(y ** x)
print(y % x)
